# project_manager.py - Professional Project Management
import os
import json
import shutil
from datetime import datetime
from pathlib import Path

class ProjectManager:
    def __init__(self):
        self.base_path = "projects"
        self.current_project = None
        os.makedirs(self.base_path, exist_ok=True)
    
    def create_project(self, name, description="", author="", genre="Visual Novel"):
        """Create a professional project structure"""
        project_id = name.lower().replace(" ", "_")
        project_path = os.path.join(self.base_path, project_id)
        
        if os.path.exists(project_path):
            # Find next available name
            counter = 1
            while os.path.exists(f"{project_path}_{counter}"):
                counter += 1
            project_path = f"{project_path}_{counter}"
            project_id = f"{project_id}_{counter}"
        
        # Create folder structure
        folders = [
            "characters",
            "scenes",
            "assets/backgrounds",
            "assets/sprites", 
            "assets/audio",
            "assets/scripts",
            "exports/renpy",
            "exports/web",
            "temp"
        ]
        
        for folder in folders:
            os.makedirs(os.path.join(project_path, folder), exist_ok=True)
        
        # Create project metadata
        metadata = {
            "project": {
                "id": project_id,
                "name": name,
                "description": description,
                "author": author,
                "genre": genre,
                "created": datetime.now().isoformat(),
                "version": "1.0.0",
                "renpy_version": "8.0.3"
            },
            "characters": [],
            "scenes": [],
            "assets": {
                "backgrounds": [],
                "sprites": [],
                "audio": []
            },
            "settings": {
                "resolution": "1920x1080",
                "language": "en",
                "default_font": "DejaVuSans.ttf"
            }
        }
        
        with open(os.path.join(project_path, "project.json"), "w", encoding="utf-8") as f:
            json.dump(metadata, f, indent=2, ensure_ascii=False)
        
        # Create basic Ren'Py script
        self.create_renpy_script(project_path, name)
        
        # Create README
        with open(os.path.join(project_path, "README.md"), "w", encoding="utf-8") as f:
            f.write(f"# {name}\n\n")
            f.write(f"{description}\n\n")
            f.write(f"## Project Information\n")
            f.write(f"- **Author**: {author}\n")
            f.write(f"- **Genre**: {genre}\n")
            f.write(f"- **Created**: {datetime.now().strftime('%Y-%m-%d')}\n")
            f.write(f"- **Tool**: Visual Novel Creator\n\n")
            f.write("## Folder Structure\n")
            f.write("- `characters/` - Character definitions and assets\n")
            f.write("- `scenes/` - Scene scripts and data\n")
            f.write("- `assets/` - Backgrounds, sprites, audio\n")
            f.write("- `exports/` - Compiled/exported versions\n")
        
        self.current_project = project_id
        return project_path
    
    def create_renpy_script(self, project_path, project_name):
        """Create basic Ren'Py script.rpy file"""
        script_content = f'''# {project_name} - Ren'Py Script
# Generated by Visual Novel Creator
# Created: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

define config.name = "{project_name}"
define gui.show_name = True

define config.version = "1.0"
define config.save_directory = "{project_name.replace(' ', '_')}"

# Screen dimensions
define config.screen_width = 1920
define config.screen_height = 1080

# Character definitions (will be auto-populated)
define mc = Character("Protagonist", color="#ffffff")

# The game starts here
label start:
    
    # Example scene
    scene bg room
    
    mc "This is the beginning of our story..."
    mc "Welcome to {project_name}!"
    
    # More content will be added here
    
    return
'''
        
        with open(os.path.join(project_path, "script.rpy"), "w", encoding="utf-8") as f:
            f.write(script_content)
    
    def add_character(self, project_id, char_data):
        """Add a character to project with proper structure"""
        project_path = os.path.join(self.base_path, project_id)
        if not os.path.exists(project_path):
            return False
        
        char_folder = char_data["name"].lower().replace(" ", "_")
        char_path = os.path.join(project_path, "characters", char_folder)
        os.makedirs(char_path, exist_ok=True)
        
        # Save character data
        char_file = os.path.join(char_path, "character.json")
        char_data["id"] = char_folder
        char_data["created"] = datetime.now().isoformat()
        char_data["image"] = f"sprites/{char_folder}/default.png"  # Placeholder
        
        with open(char_file, "w", encoding="utf-8") as f:
            json.dump(char_data, f, indent=2, ensure_ascii=False)
        
        # Update project metadata
        project_file = os.path.join(project_path, "project.json")
        with open(project_file, "r", encoding="utf-8") as f:
            metadata = json.load(f)
        
        metadata["characters"].append({
            "id": char_folder,
            "name": char_data["name"],
            "role": char_data.get("role", ""),
            "file": f"characters/{char_folder}/character.json"
        })
        
        with open(project_file, "w", encoding="utf-8") as f:
            json.dump(metadata, f, indent=2, ensure_ascii=False)
        
        # Create character dialogue template
        dialogue_file = os.path.join(char_path, "dialogue.json")
        with open(dialogue_file, "w", encoding="utf-8") as f:
            json.dump({
                "character": char_data["name"],
                "lines": [],
                "expressions": {
                    "happy": "Happy dialogue lines...",
                    "sad": "Sad dialogue lines...",
                    "angry": "Angry dialogue lines..."
                }
            }, f, indent=2, ensure_ascii=False)
        
        return True
    
    def add_scene(self, project_id, scene_data):
        """Add a scene to project"""
        project_path = os.path.join(self.base_path, project_id)
        if not os.path.exists(project_path):
            return False
        
        scene_folder = scene_data["title"].lower().replace(" ", "_")
        scene_path = os.path.join(project_path, "scenes", scene_folder)
        os.makedirs(scene_path, exist_ok=True)
        
        # Save scene data
        scene_file = os.path.join(scene_path, "scene.json")
        scene_data["id"] = scene_folder
        scene_data["created"] = datetime.now().isoformat()
        
        with open(scene_file, "w", encoding="utf-8") as f:
            json.dump(scene_data, f, indent=2, ensure_ascii=False)
        
        # Create Ren'Py scene file
        rpy_file = os.path.join(scene_path, "scene.rpy")
        with open(rpy_file, "w", encoding="utf-8") as f:
            f.write(f'''# {scene_data["title"]}
label {scene_folder}:
    
    scene {scene_data.get("location", "bg room").lower().replace(" ", "_")}
    
    "{scene_data.get("description", "Scene begins...")}"
    
    # Characters in scene: {scene_data.get("characters", "")}
    
    # Dialogue will be added here
    
    return
''')
        
        # Update project metadata
        project_file = os.path.join(project_path, "project.json")
        with open(project_file, "r", encoding="utf-8") as f:
            metadata = json.load(f)
        
        metadata["scenes"].append({
            "id": scene_folder,
            "title": scene_data["title"],
            "location": scene_data.get("location", ""),
            "characters": scene_data.get("characters", ""),
            "file": f"scenes/{scene_folder}/scene.rpy"
        })
        
        with open(project_file, "w", encoding="utf-8") as f:
            json.dump(metadata, f, indent=2, ensure_ascii=False)
        
        return True
    
    def list_projects(self):
        """List all projects"""
        projects = []
        if os.path.exists(self.base_path):
            for item in os.listdir(self.base_path):
                project_path = os.path.join(self.base_path, item)
                if os.path.isdir(project_path):
                    project_file = os.path.join(project_path, "project.json")
                    if os.path.exists(project_file):
                        try:
                            with open(project_file, "r", encoding="utf-8") as f:
                                metadata = json.load(f)
                            projects.append({
                                "id": item,
                                "name": metadata["project"]["name"],
                                "created": metadata["project"]["created"],
                                "path": project_path
                            })
                        except:
                            pass
        return projects
    
    def open_project(self, project_id):
        """Open a project"""
        project_path = os.path.join(self.base_path, project_id)
        if os.path.exists(project_path):
            self.current_project = project_id
            return project_path
        return None